all: helloWorld.exe ex03.exe ex04.exe ex05.exe ex06.exe ex07.exe ex08.exe ex09.exe ex10.exe ex11.exe ex12.exe

helloWorld.exe: helloWorld.c _OpenCLUtil.c
	gcc -o helloWorld helloWorld.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex03.exe: ex03.c _OpenCLUtil.c
	gcc -o ex03 ex03.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex04.exe: ex04.c _OpenCLUtil.c
	gcc -o ex04 ex04.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex05.exe: ex05.c _OpenCLUtil.c
	gcc -o ex05 ex05.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex06.exe: ex06.c _OpenCLUtil.c
	gcc -o ex06 ex06.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex07.exe: ex07.c _OpenCLUtil.c
	gcc -o ex07 ex07.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex08.exe: ex08.c _OpenCLUtil.c
	gcc -o ex08 ex08.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex09.exe: ex09.c _OpenCLUtil.c
	gcc -o ex09 ex09.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex10.exe: ex10.c _OpenCLUtil.c
	gcc -o ex10 ex10.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex11.exe: ex11.c _OpenCLUtil.c
	gcc -o ex11 ex11.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL

ex12.exe: ex12.c _OpenCLUtil.c
	gcc -o ex12 ex12.c _OpenCLUtil.c -L "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -lOpenCL


clean:
	del /Q /F helloWorld.exe ex03.exe ex04.exe ex05.exe ex06.exe ex07.exe ex08.exe ex09.exe ex10.exe ex11.exe ex12.exe